### ISSUE TITLE
Support uninstallation

### ISSUE THREAD

**Issue by breznak** [inilabs/libcaer#19]
of current/all versions. And all files created by libcaer on the host system. 
- either through pkg-config?
- or as `make uninstall` in the projects repository with the past cmake config

People are having problems with multiple versions staying around and causing hard to spot problems.

**Comment by llongi** [comment]
https://cmake.org/Wiki/CMake_FAQ#Can_I_do_.22make_uninstall.22_with_CMake.3F
It is possible, but I disagree strongly that this is a problem for our project to handle. Installing and uninstalling things is a problem for the system administrator and/or the package manager. Further anything we could do in cmake, at our level, would depend on something like the install_manifest.txt being there when you want to uninstall. But if the cmake files are left undisturbed, then there is no reason that you'd have any problem when installing next time. The only way you can have problems because of old libcaer copies left on the system is if they are in different places, which is a clear user error and even a "make uninstall" could not fix that. Installing a new libcaer will update all include/pkg-config files, and add a new library, and update the .so links, so that's perfectly fine. If they are in different paths due to setting a wrong CMAKE_INSTALL_PREFIX; there's no magic that can be done to fix that.
