### ISSUE TITLE
Problem on function HTML documentation

### ISSUE THREAD

**Issue by sanfans** [inilabs/libcaer#46]
At the web site in which there is the documentation (https://inilabs.github.io/libcaer/index.html)
some functions, like "caerDynapseWriteSramWords" function (on dynapse.h), are not included in the global function list, here:
https://inilabs.github.io/libcaer/globals_func.html
That happens also for other functions, mostly on dynapse.h. I noticed that this functions (that are not present in the global list) have also no documentation.

**Comment by llongi** [comment]
The documentation has been completed and fixed in the current Git include files. The inilabs.github.io site is only regenerated automatically on new releases, so when we release 2.4.0 it will automatically fix that.
If you need current documentation you can access it locally in docs/html/ and update it with 'make doc' (doxygen must be installed for it to work).
