### ISSUE TITLE
example daviscvgui.cpp doesn't compile

### ISSUE THREAD

**Issue by ru1sb** [inilabs/libcaer#55]
I'm trying to build daviscvgui.cpp with Qt under ubuntu but I am getting the error:  " ‘const struct libcaer::events::FrameEvent’ has no member named ‘getOpenCVMat’
cv::Mat cvFrame = f.getOpenCVMat(false);" 
I installed libcaer without adding openCv

**Comment by llongi** [comment]
Hi, the davis_cvgui.cpp example requires OpenCV support in libcaer to be enabled.
I've added a check now to prevent compilation if it is disabled, and have added a note in the README.
Please recompile libcaer with -DENABLE_OPENCV=1 if you want to use that example specifically.

**Comment by ru1sb** [comment]
I did so but I get this errors:
![screenshot from 2018-02-07 17-44-23](https://user-images.githubusercontent.com/35462887/35929025-cfb60852-0c2e-11e8-8264-0d585b3df586.png)

**Comment by llongi** [comment]
Undefined reference means the linker cannot find the appropriate library.
Run 'pkg-config --libs opencv' and make sure the Qt project links to all of those libraries.
I don't use the Qt IDE so I can't tell you where exactly to put that information, but since it links successfully to libcaer (-lcaer), I assume you know where to put library dependencies in Qt IDE. Just do the same as you did for libcaer, but for OpenCV.
